// Generated by Selenium IDE
import org.junit.Test;
        import org.junit.Before;
        import org.junit.After;
        import static org.junit.Assert.*;
        import static org.hamcrest.CoreMatchers.is;
        import org.openqa.selenium.By;
        import org.openqa.selenium.WebDriver;
        import org.openqa.selenium.chrome.ChromeDriver;
        import org.openqa.selenium.Dimension;
        import org.openqa.selenium.WebElement;
        import org.openqa.selenium.interactions.Actions;
        import org.openqa.selenium.JavascriptExecutor;
        import java.util.*;

public class test_web {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void test() {
        driver.get("http://automationpractice.com/index.php");
        driver.manage().window().setSize(new Dimension(1536, 864));
        {
            List<WebElement> elements = driver.findElements(By.id("block_top_menu"));
            assert(elements.size() > 0);
        }
        driver.findElement(By.linkText("Sign in")).click();
        {
            WebElement element = driver.findElement(By.id("columns"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        assertThat(driver.findElement(By.cssSelector(".page-heading")).getText(), is("AUTHENTICATION"));
        driver.findElement(By.id("email_create")).click();
        driver.findElement(By.id("email_create")).sendKeys("weverson.virgens92@gmail.com");
        driver.findElement(By.cssSelector("#SubmitCreate > span")).click();
        driver.findElement(By.id("id_gender1")).click();
        driver.findElement(By.id("customer_firstname")).click();
        driver.findElement(By.id("customer_firstname")).click();
        driver.findElement(By.id("customer_firstname")).sendKeys("Werverson");
        driver.findElement(By.id("customer_lastname")).click();
        driver.findElement(By.id("customer_lastname")).click();
        driver.findElement(By.id("customer_lastname")).sendKeys("Virgens");
        driver.findElement(By.cssSelector(".account_creation:nth-child(1) > .required:nth-child(5)")).click();
        driver.findElement(By.id("passwd")).click();
        driver.findElement(By.id("passwd")).sendKeys("imb123");
        driver.findElement(By.id("days")).click();
        {
            WebElement dropdown = driver.findElement(By.id("days"));
            dropdown.findElement(By.xpath("//option[. = 'regexp:16\\s+']")).click();
        }
        driver.findElement(By.id("months")).click();
        {
            WebElement dropdown = driver.findElement(By.id("months"));
            dropdown.findElement(By.xpath("//option[. = 'regexp:April\\s']")).click();
        }
        driver.findElement(By.id("years")).click();
        {
            WebElement dropdown = driver.findElement(By.id("years"));
            dropdown.findElement(By.xpath("//option[. = 'regexp:1992\\s+']")).click();
        }
        driver.findElement(By.id("firstname")).click();
        driver.findElement(By.cssSelector(".account_creation:nth-child(2) > .required:nth-child(3)")).click();
        driver.findElement(By.id("address1")).click();
        driver.findElement(By.id("address1")).sendKeys("St. Rua n 2");
        driver.findElement(By.id("city")).click();
        driver.findElement(By.id("city")).sendKeys("Guarujá");
        driver.findElement(By.id("id_state")).click();
        {
            WebElement dropdown = driver.findElement(By.id("id_state"));
            dropdown.findElement(By.xpath("//option[. = 'Texas']")).click();
        }
        driver.findElement(By.id("postcode")).click();
        driver.findElement(By.id("postcode")).sendKeys("000877");
        driver.findElement(By.id("phone_mobile")).click();
        driver.findElement(By.id("phone_mobile")).sendKeys("5511998877534");
        driver.findElement(By.id("alias")).click();
        driver.findElement(By.id("alias")).sendKeys("My address 1");
        driver.findElement(By.cssSelector("#submitAccount > span")).click();
        driver.findElement(By.cssSelector("ol > li")).click();
        driver.findElement(By.cssSelector("ol > li")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("ol > li"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("postcode")).click();
        driver.findElement(By.id("postcode")).click();
        {
            WebElement element = driver.findElement(By.id("postcode"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("postcode")).sendKeys("00000");
        driver.findElement(By.cssSelector("#submitAccount > span")).click();
        driver.findElement(By.id("passwd")).click();
        driver.findElement(By.id("passwd")).sendKeys("imb123");
        driver.findElement(By.cssSelector("#submitAccount > span")).click();
        driver.findElement(By.id("center_column")).click();
        assertThat(driver.findElement(By.cssSelector(".info-account")).getText(), is("Welcome to your account. Here you can manage all of your personal information and orders."));
        driver.findElement(By.cssSelector(".info-account")).click();
    }
}
